name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build command
    - name: Build
      shell: cmd
      run: '"%MSBUILD_PATH%\MSBuild.exe" Osiris/Osiris.vcxproj /p:Platform=Win32 /p:Configuration=Release'   
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: osiris.dll
        path: Osiris\Release\Osiris.dll
      
